
export const metadata = {
  title: "Foodies",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {" "}
      <h1>test</h1>
      {children}
    </div>
  );
}
