import Page from "../components/Page";

export const metadata = {
  title: "Foodies",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Page>
      <h1>Test</h1>
      {children}
    </Page>
  );
}
