"use client";
import "@/app/ui/globals.css";

import MuiBox from "@mui/material/Box";
import { roboto } from "@/app/ui/font";
import { ThemeProvider } from "@emotion/react";
import styled from "@emotion/styled";
import { useState } from "react";
import AppDrawer from "./components/Drawer";
import AppHeader from "./components/Toolbar";
import theme from "./ui/theme";

// export const metadata = {
//   title: "Foodies",
//   description: "Generated by Next.js",
// };

const AppContainer = styled(MuiBox)(({ theme }) => ({
  display: "flex",
  height: "100%",
}));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(true);

  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider theme={theme}>
          <AppContainer>
            <AppHeader setOpen={setOpen} isOpen={open} width={240} />
            <AppDrawer setOpen={setOpen} isOpen={open} width={240} />
            {children}
          </AppContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
