"use client";

import "@/app/ui/globals.css";
import { inter, roboto } from "@/app/ui/font";
import { ThemeProvider } from "@emotion/react";
import theme from "./ui/theme";

// export const metadata = {
//   title: "Foodies",
//   description: "Generated by Next.js",
// };
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
